# Generated by Django 3.2.7 on 2021-10-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVo',
        ),
    ]
